# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Generator.delete_all

Generator.create(queue:"AA1-018",project_name:"Powerton-Goodings Grove",mw:150,inservice_date:"2017 Q4",fueltype:"wind",county:"Livingston",state:"IL")
Generator.create(queue:"AA1-078",project_name:"University Park North",mw:560,inservice_date:"2015 Q4",fueltype:"natural gas",county:"Will",state:"IL")
Generator.create(queue:"AA1-086",project_name:"Blue Mound-Latham",mw:200,inservice_date:"2017 Q4",fueltype:"wind",county:"Macon",state:"IL")
Generator.create(queue:"AA1-116",project_name:"Kensington/Kankakee",mw:20,inservice_date:"2016 Q2",fueltype:"storage",county:"Kankakee",state:"IL")
Generator.create(queue:"AA1-117",project_name:"Kensington/Kankakee",mw:20,inservice_date:"2016 Q3",fueltype:"storage",county:"Kankakee",state:"IL")
Generator.create(queue:"AA1-129",project_name:"Northbrook-Skokie",mw:27,inservice_date:"2018 Q2",fueltype:"natural gas",county:"Cook",state:"IL")
Generator.create(queue:"AA1-146",project_name:"Nelson",mw:190,inservice_date:"2017 Q2",fueltype:"natural gas",county:"Lee",state:"IL")
Generator.create(queue:"AA2-030",project_name:"Nelson",mw:190,inservice_date:"2017 Q2",fueltype:"natural gas",county:"Lee",state:"IL")
Generator.create(queue:"AA2-035",project_name:"Collins",mw:1140.8,inservice_date:"2019 Q2",fueltype:"natural gas",county:"Grundy",state:"IL")
Generator.create(queue:"AA2-039",project_name:"Kewaneee 138kV",mw:150,inservice_date:"2016 Q4",fueltype:"wind",county:"Henry",state:"IL")
Generator.create(queue:"AA2-067",project_name:"Belvidere",mw:10,inservice_date:"2017 Q2",fueltype:"natural gas",county:"Boone",state:"IL")
Generator.create(queue:"AA2-106",project_name:"Bluff Point 69kV",mw:20,inservice_date:"2015 Q4",fueltype:"storage",county:"Jay",state:"IN")
Generator.create(queue:"AA2-107",project_name:"Waterman 138kV",mw:20,inservice_date:"2016 Q4",fueltype:"storage",county:"DeKalb",state:"IL")
Generator.create(queue:"AA2-123",project_name:"Marengo 34kV",mw:20,inservice_date:"2016 Q4",fueltype:"storage",county:"McHenry",state:"IL")
Generator.create(queue:"AA2-136",project_name:"Kendall",mw:1228.8,inservice_date:"2016 Q2",fueltype:"natural gas",county:"Kendall",state:"IL")
Generator.create(queue:"AA2-148",project_name:"Madison-Tanners Creek 138kV",mw:175,inservice_date:"2015 Q4",fueltype:"wind",county:"Fayette",state:"IN")
Generator.create(queue:"AB1-006",project_name:"Olive-Dequine 345kV (Meadown Lake VI)",mw:200,inservice_date:"2017 Q4",fueltype:"wind",county:"White",state:"IN")
Generator.create(queue:"O09",project_name:"Normandy",mw:212,inservice_date:"2016 Q3",fueltype:"wind",county:"Lee",state:"IL")
Generator.create(queue:"O29",project_name:"Normandy 138kV",mw:225,inservice_date:"2016 Q3",fueltype:"wind",county:"Lee",state:"IL")
Generator.create(queue:"Q39",project_name:"Kewanee 138kV",mw:105,inservice_date:"2016 Q4",fueltype:"wind",county:"Henry",state:"IL")
Generator.create(queue:"R30",project_name:"Pontiac Mid-Point 345kV",mw:500,inservice_date:"2016 Q4",fueltype:"wind",county:"Livingston",state:"IL")
Generator.create(queue:"S37",project_name:"Kankakee 138kV",mw:175,inservice_date:"2016 Q4",fueltype:"wind",county:"Kankakee",state:"IL")
Generator.create(queue:"S71",project_name:"Bluff Point 138kV",mw:120,inservice_date:"2016 Q4",fueltype:"wind",county:"Jay",state:"IN")
Generator.create(queue:"S72",project_name:"Convoy-East Lima 345kV",mw:240,inservice_date:"2016 Q4",fueltype:"wind",county:"Allen",state:"IN")
Generator.create(queue:"T143",project_name:"Hennepin",mw:250,inservice_date:"2016 Q4",fueltype:"wind",county:"Putnam",state:"IL")
Generator.create(queue:"T148",project_name:"Wempletown-Belvider 138kV",mw:100,inservice_date:"2016 Q4",fueltype:"wind",county:"Boone",state:"IL")
Generator.create(queue:"T99",project_name:"Wempletown-Belvidere 138kV",mw:100,inservice_date:"2016 Q4",fueltype:"wind",county:"Boone",state:"IL")
Generator.create(queue:"U3-021",project_name:"Silver Lake-Cherry Valley",mw:100,inservice_date:"2016 Q4",fueltype:"natural gas",county:"Boone",state:"IL")
Generator.create(queue:"U4-027",project_name:"Normandy-Kewanee 138kV",mw:100,inservice_date:"2016 Q4",fueltype:"natural gas",county:"Henry",state:"IL")
Generator.create(queue:"V3-007",project_name:"Desoto-Tanners Creek #1 345kV",mw:200,inservice_date:"2015 Q4",fueltype:"wind",county:"Randolph",state:"IN")
Generator.create(queue:"V3-009",project_name:"Desoto-Tanners Creek #2 345kV",mw:200,inservice_date:"2015 Q4",fueltype:"wind",county:"Randolph",state:"IN")
Generator.create(queue:"W2-048",project_name:"Brokaw-Lanesville",mw:62.5,inservice_date:"2015 Q4",fueltype:"wind",county:"Logan",state:"IL")
Generator.create(queue:"W3-046",project_name:"Powerton 345kV",mw:207.5,inservice_date:"2015 Q4",fueltype:"wind",county:"Mason",state:"IL")
Generator.create(queue:"W4-004",project_name:"Madison-Tanners Creek 138kV",mw:90,inservice_date:"2016 Q4",fueltype:"wind",county:"Henry",state:"IN")
Generator.create(queue:"W4-005",project_name:"Blue Mound - Latham 345kV",mw:351,inservice_date:"2016 Q4",fueltype:"wind",county:"Macon",state:"IL")
Generator.create(queue:"W4-008",project_name:"Madison-Tanners Creek 138kV",mw:90,inservice_date:"2016 Q4",fueltype:"wind",county:"Henry",state:"IN")
Generator.create(queue:"W4-033",project_name:"Wilmington",mw:10,inservice_date:"2016 Q4",fueltype:"solar",county:"Will",state:"IL")
Generator.create(queue:"X1-020",project_name:"Dumont-Greentown 765kV",mw:1500,inservice_date:"2015 Q4",fueltype:"wind",county:"Cass",state:"IN")
Generator.create(queue:"X1-087",project_name:"Stillman Valley",mw:15.3,inservice_date:"2016 Q2",fueltype:"methane",county:"Ogle",state:"IL")
Generator.create(queue:"X2-022",project_name:"Brokaw-Lanesville",mw:189,inservice_date:"2015 Q4",fueltype:"wind",county:"Logan",state:"IL")
Generator.create(queue:"X2-052",project_name:"Dumont-Olive 345kV",mw:675,inservice_date:"2018 Q2",fueltype:"natural gas",county:"Adams",state:"IN")
Generator.create(queue:"Y2-103",project_name:"Zion Energy Center",mw:945,inservice_date:"2016 Q2",fueltype:"natural gas",county:"Lake",state:"IL")
Generator.create(queue:"Y3-013",project_name:"Zion Energy Center",mw:945,inservice_date:"2016 Q2",fueltype:"natural gas",county:"Lake",state:"IL")
Generator.create(queue:"Y3-038",project_name:"Rockport Unit 1",mw:1356,inservice_date:"2016 Q2",fueltype:"coal",county:"Spencer",state:"IN")
Generator.create(queue:"Y3-089",project_name:"Kendall II",mw:1178.8,inservice_date:"2016 Q2",fueltype:"natural gas",county:"Grundy",state:"IL")
Generator.create(queue:"Y3-091",project_name:"Kendall IV",mw:1218.8,inservice_date:"2016 Q2",fueltype:"natural gas",county:"Grundy",state:"IL")
Generator.create(queue:"Z1-106",project_name:"West Chicago 34kV",mw:20,inservice_date:"2015 Q4",fueltype:"storage",county:"DuPage",state:"IL")
Generator.create(queue:"Z1-107",project_name:"Joliet 34kV",mw:20,inservice_date:"2015 Q4",fueltype:"storage",county:"Will",state:"IL")
Generator.create(queue:"Z1-108",project_name:"McHenry 34kV",mw:20,inservice_date:"2015 Q4",fueltype:"storage",county:"McHenry",state:"IL")
Generator.create(queue:"Z2-087",project_name:"Pontiac MidPoint-Brokaw 345kV",mw:200,inservice_date:"2018 Q4",fueltype:"wind",county:"Livingston",state:"IL")
Generator.create(queue:"Z2-114",project_name:"Olive 12.47kV",mw:5,inservice_date:"2016 Q4",fueltype:"solar",county:"St. Joseph",state:"IN")
Generator.create(queue:"Z2-115",project_name:"Deer Creek 12.47kV",mw:2.5,inservice_date:"2015 Q4",fueltype:"solar",county:"Grant",state:"IN")
Generator.create(queue:"Z2-116",project_name:"Twin Branch 12.47kV",mw:2.6,inservice_date:"2016 Q4",fueltype:"solar",county:"St. Joseph",state:"IN")
